title: knowledge worth spreading
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5042553
  brandStrength: 0.3574468
  lightness: 0.7255319
  brandColors:
    - '#FFFFFF'
    - '#FFA349'
    - '#766959'
    - '#090708'
    - '#B6B2AF'
  rhythmicContrast: 0.01276596
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: kiwis
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6574468
layout_spectrum: 1
