title: knowledge worth spreading
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9617021
  brandStrength: 1
  lightness: 0.6042553
  brandColors:
    - '#FFFFFF'
    - '#FFA349'
    - '#766959'
    - '#090708'
    - '#B6B2AF'
  rhythmicContrast: 0.3446808
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: kiwis
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6574468
layout_spectrum: 0.912766
